### ISSUE TITLE
佬，这个Python服务器生成的密钥怎么不能直接填入软件啊

### ISSUE THREAD

**Issue by wokeyide55** [jeanhua/safe-chat#1]

**Comment by wokeyide55** [comment]
好滴，还有一个问题打扰了，这里填本机IP运行服务器之后为什么显示不连接啊
![image](https://github.com/user-attachments/assets/0d83590c-08b7-4e11-9a23-ef25d920bf67)

**Comment by jeanhua** [comment]
那就是ip或者端口错了，端口默认是8888，服务端可以改，你可以在本机运行服务端后在客户端IP输入127.0.0.1:8888测试一下

**Comment by jeanhua** [comment]
因为这个得的是公网ip，如果是个人电脑的话公网ip是连接不到的，运营商公网ip是复用的，具体可以学习计算机网络的内容，这里不再赘述，而且对于服务器，都是直接有公网ip的，不用再次查询，所以这段代码意义不大，于是删除了
